[package]
name = "base"
authors = { workspace = true }
categories = { workspace = true }
edition = { workspace = true }
version = { workspace = true }

[dependencies]
lookup_generator = { path = "../lookup" }

thiserror = "1.0.24"
rand = "0.8.5"

